### ISSUE TITLE
[tanssi-polkadot-v1.1.0] Supplied slot number is not high enough

### ISSUE THREAD

**Issue by Chralt98** [Moonsong-Labs/moonkit#20]
[This](https://github.com/moondance-labs/moonkit/blob/c398323df2edf63ffe8afa1643d5537fdc307fd7/pallets/author-inherent/src/benchmarks.rs#L25-L29) benchmark doesn't work on this branch. It panics with [`Block invalid; Supplied slot number is not high enough`](https://github.com/moondance-labs/moonkit/blob/c398323df2edf63ffe8afa1643d5537fdc307fd7/pallets/author-inherent/src/lib.rs#L132).

It seems that [`set_slot`](https://github.com/moondance-labs/moonkit/blob/c398323df2edf63ffe8afa1643d5537fdc307fd7/primitives/nimbus-primitives/src/lib.rs#L72-L92) does not work as intended. I think just the default implementation of `set_slot` is called [here](https://github.com/moondance-labs/moonkit/blob/4ac2c442a886f925df4aa820f89a4c00a1e41eff/primitives/nimbus-primitives/src/lib.rs#L77).

I use [this implementation for `SlotBeacon`](https://github.com/moondance-labs/tanssi/blob/d422831acc78ba756732fb0390bf4522d39d097d/primitives/consensus/src/lib.rs#L66-L83). I use a similar implementation for slot(), which is:

```rust
    fn slot() -> u32 {
        use sp_consensus_aura::{Slot, AURA_ENGINE_ID};

        let digests = frame_system::Pallet::<ContainerRuntime>::digest();

        let slot = digests
            .convert_first(|item| item.pre_runtime_try_to::<Slot>(&AURA_ENGINE_ID))
            .unwrap_or_default();

        let slot: u64 = slot.into();
        slot as u32
    }
```

So I guess slot is zero and because of that it is not high enough. So, how could I change the slot to 1 or higher? `set_slot` doesn't seem to be the right approach..

**Comment by girazoki** [comment]
It probably is because we are missing a feature flag related to runtime-benchmarks in our primtiives, will dig into it a bit more. Thank you for reporting @Chralt98!

**Comment by girazoki** [comment]
@Chralt98 this PR should fix your issues https://github.com/moondance-labs/tanssi/pull/389
